### ISSUE TITLE
catkin_make error 

### ISSUE THREAD

**Issue by ashfaqayaaz98** [aniskoubaa/ros_essentials_cpp#5]
/home/ashfaqayaaz/catkin_ws/src/ros_essentials_cpp/src/topic03_perception/cpp/open_copy.cpp:1:10: fatal error: highgui.h: No such file or directory
    1 | #include <highgui.h>
      |          ^~~~~~~~~~~
compilation terminated.

Invoking "make -j4 -l4" failed

**Comment by vineet-rarisystems** [comment]
I am getting a similar error:
```
Traceback (most recent call last):
  File "/opt/ros/melodic/share/gencpp/cmake/../../../lib/gencpp/gen_cpp.py", line 43, in <module>
    import genmsg.template_tools
  File "/opt/ros/melodic/lib/python2.7/dist-packages/genmsg/template_tools.py", line 39, in <module>
    import em
ImportError: No module named em
ros_essentials_cpp/CMakeFiles/ros_essentials_cpp_generate_messages_cpp.dir/build.make:70: recipe for target '/home/vineet/catkin_ws/devel/include/ros_essentials_cpp/FibonacciGoal.h' failed
make[2]: *** [/home/vineet/catkin_ws/devel/include/ros_essentials_cpp/FibonacciGoal.h] Error 1
CMakeFiles/Makefile2:1591: recipe for target 'ros_essentials_cpp/CMakeFiles/ros_essentials_cpp_generate_messages_cpp.dir/all' failed
make[1]: *** [ros_essentials_cpp/CMakeFiles/ros_essentials_cpp_generate_messages_cpp.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j1 -l1" failed
```

Is there a solution to this ??

**Comment by VineetTambe** [comment]
I am getting a similar error:
```

Traceback (most recent call last):
  File "/opt/ros/melodic/share/gencpp/cmake/../../../lib/gencpp/gen_cpp.py", line 43, in <module>
    import genmsg.template_tools
  File "/opt/ros/melodic/lib/python2.7/dist-packages/genmsg/template_tools.py", line 39, in <module>
    import em
ImportError: No module named em
ros_essentials_cpp/CMakeFiles/ros_essentials_cpp_generate_messages_cpp.dir/build.make:70: recipe for target '/home/vineet/catkin_ws/devel/include/ros_essentials_cpp/FibonacciGoal.h' failed
make[2]: *** [/home/vineet/catkin_ws/devel/include/ros_essentials_cpp/FibonacciGoal.h] Error 1
CMakeFiles/Makefile2:1591: recipe for target 'ros_essentials_cpp/CMakeFiles/ros_essentials_cpp_generate_messages_cpp.dir/all' failed
make[1]: *** [ros_essentials_cpp/CMakeFiles/ros_essentials_cpp_generate_messages_cpp.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j1 -l1" failed
```
Has anyone found a solution to this ?

**Comment by VineetTambe** [comment]
>   import e

The solution is to install the "empy" and the "pyyaml" packages if not installed already
```
pip install empy
pip install pyyaml
```

**Comment by beichenningxue** [comment]
same error

**Comment by SalmaEl-gohary** [comment]
- open the file mentioned in the error  "catkin_ws/src/ros_essentials_cpp/src/topic03_perception/cpp/open_copy.cpp"
- change <highgui.h> to become  <opencv2/highgui/highgui.hpp>
